import type { Metadata } from 'next'
import { Inter, Khula } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const khula = Khula({
  subsets: ['latin'],
  variable: '--font-khula',
  weight: ['300', '700', '800'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${khula.className} h-screen w-screen flex flex-col justify-center items-center`}
      >
        {children}
      </body>
    </html>
  )
}
